// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct BasketMarketClientProgram;

impl BasketMarketClientProgram {
    pub const ROUTE_ID_BASKET_MARKET: u8 = 1;
}

impl sails_rs::client::Program for BasketMarketClientProgram {}

pub trait BasketMarketClient {
    type Env: sails_rs::client::GearEnv;
    fn basket_market(
        &self,
    ) -> sails_rs::client::Service<basket_market::BasketMarketImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> BasketMarketClient
    for sails_rs::client::Actor<BasketMarketClientProgram, E>
{
    type Env = E;
    fn basket_market(
        &self,
    ) -> sails_rs::client::Service<basket_market::BasketMarketImpl, Self::Env> {
        self.service(BasketMarketClientProgram::ROUTE_ID_BASKET_MARKET)
    }
}
pub trait BasketMarketClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Constructor. `owner` is set to the message source (the deployer/operator).
    /// Named `init` because `new` is a reserved word on the Solidity ABI path.
    fn init(
        self,
        settler_role: ActorId,
        liveness_seconds: u64,
    ) -> sails_rs::client::PendingCtor<BasketMarketClientProgram, io::Init, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> BasketMarketClientCtors
    for sails_rs::client::Deployment<BasketMarketClientProgram, E>
{
    type Env = E;
    fn init(
        self,
        settler_role: ActorId,
        liveness_seconds: u64,
    ) -> sails_rs::client::PendingCtor<BasketMarketClientProgram, io::Init, Self::Env> {
        self.pending_ctor((settler_role, liveness_seconds))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Init (settler_role: ActorId, liveness_seconds: u64) -> (), 0);
}

pub mod basket_market {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum Error {
        Unauthorized,
        ZeroValue,
        InsufficientBalance,
        PoolInsufficient,
        BasketNotFound,
        BasketNotActive,
        NoItems,
        TooManyItems,
        InvalidWeights,
        DuplicateBasketItem,
        NameTooLong,
        DescriptionTooLong,
        SettlementNotFound,
        SettlementNotProposed,
        SettlementAlreadyExists,
        SettlementNotFinalized,
        ChallengeDeadlineNotPassed,
        InvalidIndexAtCreation,
        AlreadyClaimed,
        NothingToClaim,
        PositionNotFound,
        MathOverflow,
        WvaraTransferFailed,
        EthTransferFailed,
        UnsupportedCollateral,
        InvalidItemsPayload,
    }

    pub trait BasketMarket {
        type Env: sails_rs::client::GearEnv;
        /// Place a bet by spending the caller's free ledger balance. No value
        /// attached. `shares == amount`. The staked amount is debited here; net
        /// pool accounting happens at claim time.
        ///
        /// `collateral` is `0 = Eth`, `1 = Wvara`.
        fn bet_on_basket(
            &mut self,
            basket_id: u64,
            collateral: u16,
            amount: u128,
            index_at_creation_bps: u16,
        ) -> sails_rs::client::PendingCall<io::BetOnBasket, Self::Env>;
        /// Claim a settled position. Credits the user's ledger with the payout and
        /// reconciles the house pool: net winnings come OUT of the pool, net losses
        /// flow INTO the pool. No value attached (credit is to the internal ledger).
        fn claim(&mut self, basket_id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env>;
        /// Create an Active basket. No collateral is attached.
        ///
        /// `items` is a SCALE-encoded `Vec<BasketItem>` blob (ABI-safe `Vec<u8>`).
        fn create_basket(
            &mut self,
            name: String,
            description: String,
            items: Vec<u8>,
        ) -> sails_rs::client::PendingCall<io::CreateBasket, Self::Env>;
        /// Deposit native ETH; the attached message value is credited to the
        /// caller's Eth ledger balance.
        fn deposit_eth(&mut self) -> sails_rs::client::PendingCall<io::DepositEth, Self::Env>;
        /// Deposit wVARA. wVARA is an ERC-20 on the Ethereum side; the intended
        /// mechanism is approve(programMirror) + program-side transfer_from.
        ///
        fn deposit_wvara(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::DepositWvara, Self::Env>;
        /// Finalize a proposed settlement once the challenge window has passed.
        fn finalize_settlement(
            &mut self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeSettlement, Self::Env>;
        /// Free balance for `user` in `collateral` (`0 = Eth`, `1 = Wvara`).
        fn get_balance(
            &self,
            user: ActorId,
            collateral: u16,
        ) -> sails_rs::client::PendingCall<io::GetBalance, Self::Env>;
        /// Returns a SCALE-encoded `Vec<(Collateral, u128)>` of all free balances.
        fn get_balances(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetBalances, Self::Env>;
        /// Returns a SCALE-encoded `Basket`. Errors via `unwrap_result` if missing.
        fn get_basket(&self, id: u64) -> sails_rs::client::PendingCall<io::GetBasket, Self::Env>;
        fn get_basket_count(&self) -> sails_rs::client::PendingCall<io::GetBasketCount, Self::Env>;
        /// Returns a SCALE-encoded `Config`.
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env>;
        /// House pool balance for `collateral` (`0 = Eth`, `1 = Wvara`).
        fn get_pool(
            &self,
            collateral: u16,
        ) -> sails_rs::client::PendingCall<io::GetPool, Self::Env>;
        /// Returns a SCALE-encoded `Vec<Position>` for `user`.
        fn get_positions(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env>;
        /// Returns a SCALE-encoded `Option<Settlement>` for `basket_id`.
        fn get_settlement(
            &self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetSettlement, Self::Env>;
        /// Propose a settlement (settler role). Opens the challenge window.
        ///
        /// `item_resolutions` is a SCALE-encoded `Vec<Outcome>` blob (ABI-safe
        /// `Vec<u8>`).
        fn propose_settlement(
            &mut self,
            basket_id: u64,
            item_resolutions: Vec<u8>,
            index_bps: u16,
        ) -> sails_rs::client::PendingCall<io::ProposeSettlement, Self::Env>;
        /// Seed the ETH house pool with the attached message value (operator only).
        /// Returns the new pool balance.
        fn seed_pool_eth(&mut self) -> sails_rs::client::PendingCall<io::SeedPoolEth, Self::Env>;
        /// Seed the wVARA house pool by `amount` (operator only).
        ///
        fn seed_pool_wvara(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::SeedPoolWvara, Self::Env>;
        /// Withdraw native ETH: debit the ledger and return the value to the caller
        /// via the reply (the ethexe value-egress primitive).
        fn withdraw_eth(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawEth, Self::Env>;
        /// Withdraw ETH from the house pool back to the operator (operator only).
        fn withdraw_pool_eth(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawPoolEth, Self::Env>;
        /// Withdraw wVARA from the house pool back to the operator (operator only).
        ///
        fn withdraw_pool_wvara(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawPoolWvara, Self::Env>;
        /// Withdraw wVARA: debit the ledger and release wVARA back to the caller.
        ///
        fn withdraw_wvara(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawWvara, Self::Env>;
    }

    pub struct BasketMarketImpl;

    impl sails_rs::client::Identifiable for BasketMarketImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([160, 70, 140, 180, 239, 212, 10, 107]);
    }

    impl<E: sails_rs::client::GearEnv> BasketMarket for sails_rs::client::Service<BasketMarketImpl, E> {
        type Env = E;
        fn bet_on_basket(
            &mut self,
            basket_id: u64,
            collateral: u16,
            amount: u128,
            index_at_creation_bps: u16,
        ) -> sails_rs::client::PendingCall<io::BetOnBasket, Self::Env> {
            self.pending_call((basket_id, collateral, amount, index_at_creation_bps))
        }
        fn claim(&mut self, basket_id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn create_basket(
            &mut self,
            name: String,
            description: String,
            items: Vec<u8>,
        ) -> sails_rs::client::PendingCall<io::CreateBasket, Self::Env> {
            self.pending_call((name, description, items))
        }
        fn deposit_eth(&mut self) -> sails_rs::client::PendingCall<io::DepositEth, Self::Env> {
            self.pending_call(())
        }
        fn deposit_wvara(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::DepositWvara, Self::Env> {
            self.pending_call((amount,))
        }
        fn finalize_settlement(
            &mut self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeSettlement, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn get_balance(
            &self,
            user: ActorId,
            collateral: u16,
        ) -> sails_rs::client::PendingCall<io::GetBalance, Self::Env> {
            self.pending_call((user, collateral))
        }
        fn get_balances(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetBalances, Self::Env> {
            self.pending_call((user,))
        }
        fn get_basket(&self, id: u64) -> sails_rs::client::PendingCall<io::GetBasket, Self::Env> {
            self.pending_call((id,))
        }
        fn get_basket_count(&self) -> sails_rs::client::PendingCall<io::GetBasketCount, Self::Env> {
            self.pending_call(())
        }
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env> {
            self.pending_call(())
        }
        fn get_pool(
            &self,
            collateral: u16,
        ) -> sails_rs::client::PendingCall<io::GetPool, Self::Env> {
            self.pending_call((collateral,))
        }
        fn get_positions(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env> {
            self.pending_call((user,))
        }
        fn get_settlement(
            &self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetSettlement, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn propose_settlement(
            &mut self,
            basket_id: u64,
            item_resolutions: Vec<u8>,
            index_bps: u16,
        ) -> sails_rs::client::PendingCall<io::ProposeSettlement, Self::Env> {
            self.pending_call((basket_id, item_resolutions, index_bps))
        }
        fn seed_pool_eth(&mut self) -> sails_rs::client::PendingCall<io::SeedPoolEth, Self::Env> {
            self.pending_call(())
        }
        fn seed_pool_wvara(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::SeedPoolWvara, Self::Env> {
            self.pending_call((amount,))
        }
        fn withdraw_eth(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawEth, Self::Env> {
            self.pending_call((amount,))
        }
        fn withdraw_pool_eth(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawPoolEth, Self::Env> {
            self.pending_call((amount,))
        }
        fn withdraw_pool_wvara(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawPoolWvara, Self::Env> {
            self.pending_call((amount,))
        }
        fn withdraw_wvara(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawWvara, Self::Env> {
            self.pending_call((amount,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(BetOnBasket (basket_id: u64, collateral: u16, amount: u128, index_at_creation_bps: u16) -> u128 | super::Error, 0, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Claim (basket_id: u64) -> u128 | super::Error, 1, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CreateBasket (name: String, description: String, items: Vec<u8>) -> u64 | super::Error, 2, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(DepositEth () -> u128 | super::Error, 3, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(DepositWvara (amount: u128) -> u128 | super::Error, 4, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(FinalizeSettlement (basket_id: u64) -> () | super::Error, 5, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetBalance (user: ActorId, collateral: u16) -> u128 | super::Error, 6, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetBalances (user: ActorId) -> Vec<u8>, 7, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetBasket (id: u64) -> Vec<u8> | super::Error, 8, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetBasketCount () -> u64, 9, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetConfig () -> Vec<u8>, 10, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetPool (collateral: u16) -> u128 | super::Error, 11, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetPositions (user: ActorId) -> Vec<u8>, 12, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetSettlement (basket_id: u64) -> Vec<u8>, 13, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ProposeSettlement (basket_id: u64, item_resolutions: Vec<u8>, index_bps: u16) -> () | super::Error, 14, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SeedPoolEth () -> u128 | super::Error, 15, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SeedPoolWvara (amount: u128) -> u128 | super::Error, 16, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(WithdrawEth (amount: u128) -> () | super::Error, 17, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(WithdrawPoolEth (amount: u128) -> () | super::Error, 18, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(WithdrawPoolWvara (amount: u128) -> () | super::Error, 19, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(WithdrawWvara (amount: u128) -> () | super::Error, 20, <super::BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum BasketMarketEvents {
            #[codec(index = 0)]
            BasketCreated(u64, [u8; 32]),
            #[codec(index = 1)]
            BetPlaced(u64, [u8; 32], u16, u128),
            #[codec(index = 2)]
            Claimed(u64, [u8; 32], u128),
            #[codec(index = 3)]
            Deposited([u8; 32], u16, u128),
            #[codec(index = 4)]
            PoolSeeded(u16, u128),
            #[codec(index = 5)]
            PoolWithdrawn(u16, u128),
            #[codec(index = 6)]
            SettlementFinalized(u64, u64),
            #[codec(index = 7)]
            SettlementProposed(u64, u16, u64),
            #[codec(index = 8)]
            Withdrawn([u8; 32], u16, u128),
        }

        impl BasketMarketEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::BasketCreated { .. } => 0,
                    Self::BetPlaced { .. } => 1,
                    Self::Claimed { .. } => 2,
                    Self::Deposited { .. } => 3,
                    Self::PoolSeeded { .. } => 4,
                    Self::PoolWithdrawn { .. } => 5,
                    Self::SettlementFinalized { .. } => 6,
                    Self::SettlementProposed { .. } => 7,
                    Self::Withdrawn { .. } => 8,
                }
            }
        }

        impl sails_rs::client::Event for BasketMarketEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for BasketMarketEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <BasketMarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for BasketMarketImpl {
            type Event = BasketMarketEvents;
        }
    }
}
